sudo: false
language: ruby
rvm:
  - 2.2.2
cache: bundler
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
bundler_args: --without test --jobs 3 --retry 3
before_install:
  - openssl aes-256-cbc -K $encrypted_452262c28521_key -iv $encrypted_452262c28521_iv -in id_rsa_rorlakr_rrails_guides_travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - gem install bundler
before_script:
  - echo -e "Host guides.rorlab.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - bundle update
script: "cd guides && bundle exec rake guides:generate:html:ko:publish ALL=1"
branches:
  only:
    - guides-ko
